# -*- coding: utf-8 -*-
"""python專題.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1InPZ1cEcXXjl3HR7whBJPU18sAEjQfF1
"""

# =========================================================
# 0. Environment / Install
# =========================================================
!nvidia-smi

# 解決 scipy.linalg 導入錯誤，指定安裝 1.12.0 版本
!pip install scipy==1.12.0
!pip install bitsandbytes
!pip install accelerate
!pip install bertopic
!pip install numpy
!pip install pandas
!pip install transformers
!pip install gensim
!pip install scikit-learn
!pip install xarray plotly

# 若尚未安裝 spaCy 英文模型，請先執行：
!python -m spacy download en_core_web_sm

# =========================================================
# 1. Imports
# =========================================================
import csv
import re
import openpyxl
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk
import spacy
import gensim
import gensim.corpora as corpora
import transformers

from torch import bfloat16
from huggingface_hub import login
from huggingface_hub import create_repo
from huggingface_hub import HfApi
from huggingface_hub import snapshot_download
import os
import pickle
import json

from transformers import pipeline
from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import silhouette_score, silhouette_samples

from bertopic import BERTopic
from bertopic.representation import TextGeneration
from bertopic.vectorizers import ClassTfidfTransformer

from sentence_transformers import SentenceTransformer
from umap import UMAP
from gensim.models.coherencemodel import CoherenceModel

from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer


# =========================================================
# 2. NLTK Resources
# =========================================================
nltk.download("wordnet")
nltk.download("omw-1.4")
nltk.download("punkt")
nltk.download("averaged_perceptron_tagger")

from google.colab import userdata
from sklearn.metrics.pairwise import cosine_similarity

# =========================================================
# 3. Basic Config
# =========================================================
model_id = "meta-llama/Llama-2-7b-chat-hf"

input_excel_path = "preprocessed_document.xlsx"
custom_stop_words_path = "custom_stop_words.xlsx"
temp_csv_path = "sample.csv"

preprocessed_output_path = "preprocessed_test.xlsx"
embedding_output_path = "sentence_embeddings_with_text.xlsx"
topics_over_time_output_path = "topics_over_time.xlsx"

# 這裡改成你的「申請日期」欄位名稱
# 例如可能是 "Application Date"、"Priority Date"、"Patent Date"
publication_date_col = "Publication Date"


# =========================================================
# 4. Read Excel -> Convert to CSV -> Read CSV
#    (保留你原本流程)
# =========================================================
mydata = pd.read_excel(input_excel_path)

csv_writer = csv.writer(open(temp_csv_path, "w", newline="", encoding="utf-8-sig"))
workbook_active_sheet = openpyxl.load_workbook(input_excel_path).active

for row_cells in workbook_active_sheet.rows:
    row_values = [cell.value for cell in row_cells]
    csv_writer.writerow(row_values)

data = pd.read_csv(temp_csv_path)

test = data["Processed"].fillna("")


# =========================================================
# 5. Build Time Variable for Dynamic Topic Modeling
#    時間 = 專利申請年
# =========================================================
# 若欄位是完整日期，轉 datetime 再取 year
# 若欄位本身就是年份，to_datetime 也通常可處理
publication_date_raw = data[publication_date_col]

publication_date = pd.to_datetime(publication_date_raw, errors="coerce")
publication_year = publication_date.dt.year

# 移除沒有文件內容或沒有年份的資料
valid_mask = test.notna() & publication_year.notna()

test = test[valid_mask].reset_index(drop=True)
publication_year = publication_year[valid_mask].astype(int).reset_index(drop=True)

# BERTopic topics_over_time 的 timestamps 要和 documents 一一對應
timestamps = publication_year.tolist()

print("文件數量:", len(test))
print("年份範圍:", publication_year.min(), "to", publication_year.max())

# =========================================================
# 6. spaCy + Stopwords
# =========================================================
nlp = spacy.load("en_core_web_sm")

spacy_stopwords = spacy.lang.en.stop_words.STOP_WORDS
custom_stop_words_df = pd.read_excel(custom_stop_words_path, header=None)

excel_stop_words = custom_stop_words_df[0].tolist()
excel_stop_words = [str(word).strip().lower() for word in excel_stop_words if pd.notna(word)]

spacy_stopwords.update(excel_stop_words)

print(f"Total stop words: {len(spacy_stopwords)}")

for word in spacy_stopwords:
    if isinstance(word, str):
        nlp.vocab[word].is_stop = True

print("Custom stop words have been added successfully.")

stop_words_list = list(spacy_stopwords)


# =========================================================
# 7. Lemmatizer + POS Mapping
# =========================================================
lemmatizer = WordNetLemmatizer()

def get_wordnet_pos(pos_tag):
    """Map spaCy POS tag to WordNet POS tag."""
    tag_dict = {
        "ADJ": wordnet.ADJ,
        "NOUN": wordnet.NOUN,
        "VERB": wordnet.VERB,
        "ADV": wordnet.ADV,
    }
    return tag_dict.get(pos_tag, wordnet.NOUN)


# =========================================================
# 8. Text Preprocessing
# =========================================================
def preprocess_text(text):
    if pd.isna(text):
        return ""

    text = re.sub(r"\s+", " ", re.sub(r"\d", "", re.sub(r"[^\w\s]", "", text.lower())))
    doc = nlp(text)

    lemmatized_tokens = [
        lemmatizer.lemmatize(token.text, get_wordnet_pos(token.pos_))
        for token in doc
        if token.text not in stop_words_list
    ]

    return " ".join(lemmatized_tokens)

preprocessed_test = [preprocess_text(doc) for doc in test]

df_preprocessed = pd.DataFrame({
    "Publication_Year": publication_year,
    "Preprocessed_test": preprocessed_test
})
df_preprocessed.to_excel(preprocessed_output_path, index=False)

print(f"預處理後的文檔已保存到 {preprocessed_output_path}")

# =========================================================
# 9. BitsAndBytes 4-bit Quantization Config
# =========================================================
bnb_config = transformers.BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=bfloat16,
)


# =========================================================
# 10. Hugging Face Login + Load Llama 2
# =========================================================
hf_token = userdata.get("HF_TOKEN")
login(token=hf_token)

tokenizer = transformers.AutoTokenizer.from_pretrained(model_id)

model = transformers.AutoModelForCausalLM.from_pretrained(
    model_id,
    trust_remote_code=True,
    quantization_config=bnb_config,
    device_map="auto",
)

model.eval()

generator = pipeline(
    model=model,
    tokenizer=tokenizer,
    task="text-generation",
    temperature=0.1,
    max_new_tokens=600,
    repetition_penalty=1.1,
)


# =========================================================
# 11. Quick Test Generation
# =========================================================
prompt = "Could you explain to me how 4-bit quantization works as if I am 5?"
res = generator(prompt)
print(res[0]["generated_text"])

system_prompt_label = """
<s>[INST] <<SYS>>
You are an expert assistant for analyzing patent technologies.
Your task is to read patent documents that belong to the same topic cluster
and generate a short topic label.

The label should:
- capture the shared technological theme
- be concise and specific
- contain no more than 8 words
- avoid punctuation-heavy or sentence-style outputs

Return only the label text.
<</SYS>>
"""

example_prompt_label = """
I have a topic that contains the following patent documents:

- A flow control valve system for fuel cell applications includes a rotating valve structure and shaft mechanism designed to improve sealing performance while minimizing abrasion between the valve seat and valve structure.
- A cathode oxygen deficiency control method for fuel cell systems adjusts controller power consumption and heater operation to improve durability and prevent performance deterioration.
- A fuel cell automobile power system integrates an inverter, motor, rechargeable energy source, and cable configuration to improve reliability.

The topic is described by the following keywords:
'fuel cell, valve system, power control, durability, inverter, sealing, vehicle'

Based on the information above, give a short label for this topic.
[/INST]
Fuel Cell Power Control Systems
"""

main_prompt_label = """
[INST]
I have a topic that contains the following documents:
[DOCUMENTS]

The topic is described by the following keywords:
'[KEYWORDS]'.

Based on the information above, give a short label for this topic.
[/INST]
"""

prompt_label = system_prompt_label + example_prompt_label + main_prompt_label

# =========================================================
# 12. Prompt Design for BERTopic Topic Representation
# =========================================================
system_prompt = """
<s>[INST] <<SYS>>
You are an expert assistant for analyzing patent technologies.
Your task is to read multiple patent documents that belong to the same topic cluster and generate a concise technical summary describing the common technological theme.

Focus on:
- the shared engineering concepts
- the main technological innovation
- the primary application domain

Avoid describing documents individually. Instead, synthesize the overall technology represented by the topic.

Write the summary in clear and concise technical language.
<</SYS>>
"""

example_prompt = """
<s>[INST]
I have a topic that contains the following patent documents:
- A flow control valve system for fuel cell applications includes a rotating valve structure and shaft mechanism designed to improve sealing performance while minimizing abrasion between the valve seat and valve structure. A lip seal is used to enhance sealing reliability and suppress sliding wear during valve operation.
- A fuel cell automobile power system integrates an inverter, motor, rechargeable energy source, and cable configuration. Independent power cables connect the inverter and power source to improve reliability, simplify maintenance, and reduce phase differences in the electrical distribution system.
- A cathode oxygen deficiency control method for fuel cell systems adjusts controller power consumption and heater operation to improve durability and prevent performance deterioration, particularly during cold-start and regenerative braking conditions.
- A regenerative peroxide-based energy storage system generates electricity through catalytic reactions using peroxide solutions and water. The system integrates hydrogen tanks, oxygen tanks, and catalytic energy conversion units to provide efficient electrical power generation.
- A closed-system reactant and waste storage apparatus maintains balance between reactant storage and waste storage using pressure-resistant materials and composite structures. The system supports underwater or autonomous energy generation devices using hydrogen-generating reactions.

The topic is described by the following keywords:
'fuel cell, hydrogen energy, valve system, power control, energy storage, reactor system, catalytic reaction, hydrogen generation, battery technology'

Please analyze the documents and keywords above and summarize the **technological theme** of this topic.

Your summary should:
- focus on the core engineering concepts shared across these patents
- describe the main technological innovation
- explain the primary application domain

Write the summary in concise sentences.
[/INST]
This topic focuses on engineering technologies related to hydrogen-based energy systems and fuel cell power management. The inventions involve control valves, catalytic reactors, hydrogen generation mechanisms, and advanced energy storage systems such as redox flow batteries and chemical energy cycles designed to improve energy conversion efficiency, durability, and system reliability. These technologies are primarily applied in hydrogen fuel cell vehicles, autonomous power systems, and renewable energy storage applications.
"""

main_prompt = """
[INST]
I have a topic that contains the following documents:
[DOCUMENTS]
The topic is described by the following keywords:
'[KEYWORDS]'.
Based on the information above, summarize the technological theme of this topic.
[/INST]
"""

prompt_summary = system_prompt + example_prompt + main_prompt

llama2 = TextGeneration(generator, prompt=prompt)

llama2_label = TextGeneration(
    generator,
    prompt=prompt_label,
    nr_docs=5,
    diversity=0.2
)

llama2_summary = TextGeneration(
    generator,
    prompt=prompt_summary,
    nr_docs=5,
    diversity=0.2
)

# =========================================================
# 13. Sentence Embedding
# =========================================================
# sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
sentence_model = SentenceTransformer("all-mpnet-base-v2")

embeddings = sentence_model.encode(preprocessed_test, show_progress_bar=True)


# =========================================================
# 14. UMAP Dimensionality Reduction
# =========================================================
umap_model = UMAP(
    n_neighbors=15,
    n_components=2,
    min_dist=0.1,
    metric="cosine",
    random_state=42
)

umap_embeddings = umap_model.fit_transform(embeddings)


# =========================================================
# 15. Save Embeddings
# =========================================================
df_embeddings = pd.DataFrame(embeddings)
df_embeddings.insert(0, "Text", preprocessed_test)
df_embeddings.to_excel(embedding_output_path, index=False)

# =========================================================
# 16. Topic Diversity Function
# =========================================================
def calculate_topic_diversity(top_words_per_topic):
    all_words = [word for topic in top_words_per_topic for word in topic]
    unique_words = set(all_words)
    diversity = len(unique_words) / len(all_words)
    return diversity

# =========================================================
# 17. Topic Modeling Evaluation
# =========================================================
coherence_scores = {}
diversity_scores = {}

for num_topics in [18]:
    cluster_model = KMeans(n_clusters=num_topics, random_state=42)

    vectorizer_model = CountVectorizer(
        stop_words=stop_words_list,
        ngram_range=(1, 2),
        lowercase=True,
        min_df=10
    )

    ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

    representation_model = {
        "Main": llama2_label,
        "Summary": llama2_summary
    }

    topic_model = BERTopic(
        embedding_model=sentence_model,
        umap_model=umap_model,
        hdbscan_model=cluster_model,
        vectorizer_model=vectorizer_model,
        ctfidf_model=ctfidf_model,
        representation_model=representation_model,
        top_n_words=15,
        verbose=True,
        calculate_probabilities=False,
    )

    topics, probs = topic_model.fit_transform(preprocessed_test, embeddings)

    # ---- Coherence (Embedding-based semantic coherence) ----
        # ---- Coherence (Embedding-based semantic coherence) ----
    topic_data = topic_model.get_topics()
    topic_words = []

    for topic_id, topic_terms in topic_data.items():
        if topic_id == -1:
            continue
        if topic_terms is None or topic_terms is False:
            continue
        if not isinstance(topic_terms, list) or len(topic_terms) == 0:
            continue

        words = [word for word, _ in topic_terms[:15] if isinstance(word, str) and word.strip() != ""]
        if len(words) >= 2:
            topic_words.append(words)

    if len(topic_words) == 0:
        coherence = None
    else:
        topic_scores = []

        for words in topic_words:
            word_embeddings = sentence_model.encode(words, show_progress_bar=False)
            centroid = np.mean(word_embeddings, axis=0, keepdims=True)
            sims = cosine_similarity(word_embeddings, centroid).flatten()
            topic_scores.append(float(np.mean(sims)))

        coherence = float(np.mean(topic_scores)) if len(topic_scores) > 0 else None
    coherence_scores[num_topics] = coherence

    # ---- Diversity ----
    topic_data = topic_model.get_topics()
    top_n = 15
    top_words_per_topic = []

    for topic_id, topic_terms in topic_data.items():
        if topic_id == -1:
            continue
        if topic_terms is None or topic_terms is False:
            continue
        if not isinstance(topic_terms, list) or len(topic_terms) == 0:
            continue

        words = [word for word, _ in topic_terms[:top_n] if isinstance(word, str) and word.strip() != ""]
        if len(words) > 0:
            top_words_per_topic.append(words)

    diversity = calculate_topic_diversity(top_words_per_topic) if len(top_words_per_topic) > 0 else None
    diversity_scores[num_topics] = diversity

    print(
        f"Number of Topics: {num_topics}, "
        f"Coherence Score: {coherence}, "
        f"Diversity Score: {diversity}"
    )

print(coherence_scores)
print(diversity_scores)

'''
# =========================================================
# 18. Save Evaluation Results to Excel
# =========================================================
results_df = pd.DataFrame({
    "Number_of_Topics": list(coherence_scores.keys()),
    "Coherence_Score": list(coherence_scores.values()),
    "Diversity_Score": [diversity_scores[k] for k in coherence_scores.keys()]
})

# 依 topic 數排序
results_df = results_df.sort_values("Number_of_Topics").reset_index(drop=True)

# 存成 Excel
results_df.to_excel("topic_model_evaluation.xlsx", index=False)

print(results_df)
print("已儲存為 topic_model_evaluation.xlsx")
'''

topics_over_time = topic_model.topics_over_time(
        docs=preprocessed_test,
        timestamps=timestamps,
        nr_bins=len(sorted(set(timestamps)))
    )

# =========================================================
# 18. Save BERTopic Model (.pkl) + Excel (.xlsx with sheets)
# =========================================================

save_dir = "bertopic_model_18"
os.makedirs(save_dir, exist_ok=True)

# -------------------------
# 1. Save BERTopic model as pkl
# -------------------------
with open(os.path.join(save_dir, "bertopic_model.pkl"), "wb") as f:
    pickle.dump(topic_model, f)

print("✅ Saved model: bertopic_model.pkl")

# -------------------------
# 2. Prepare document_embeddings sheet
# -------------------------
# embeddings: shape = (n_docs, embedding_dim)
df_document_embeddings = pd.DataFrame(embeddings)
df_document_embeddings.insert(0, "Document", preprocessed_test)
df_document_embeddings.insert(1, "Topic", topics)
df_document_embeddings.insert(2, "Timestamp", timestamps)

# 欄名改成較清楚的格式
embedding_cols = ["Document", "Topic", "Timestamp"] + [f"emb_{i}" for i in range(embeddings.shape[1])]
df_document_embeddings.columns = embedding_cols

# -------------------------
# 3. Prepare topics_over_time sheet
# -------------------------
df_topics_over_time = topics_over_time.copy()

# -------------------------
# 4. Save both sheets into one Excel file
# -------------------------
excel_output_path = os.path.join(save_dir, "bertopic_outputs.xlsx")

with pd.ExcelWriter(excel_output_path, engine="openpyxl") as writer:
    df_document_embeddings.to_excel(writer, sheet_name="document_embeddings", index=False)
    df_topics_over_time.to_excel(writer, sheet_name="topics_over_time", index=False)

print(f"✅ Saved Excel with sheets: {excel_output_path}")

# -------------------------
# 5. (Optional) Save topic info too
# -------------------------
topic_info_path = os.path.join(save_dir, "topic_info.xlsx")
topic_model.get_topic_info().to_excel(topic_info_path, index=False)
print(f"✅ Saved topic info: {topic_info_path}")

# =========================================================
# Upload BERTopic artifacts folder to Hugging Face
# =========================================================

# 1. 先登入（若你已登入可略過）
# login()

# 2. 你的本地資料夾
save_dir = "bertopic_model_18"

# 3. 檢查模型檔是否存在
model_path = os.path.join(save_dir, "bertopic_model.pkl")
if not os.path.exists(model_path):
    raise FileNotFoundError(f"找不到模型檔：{model_path}")

# 4. Repo ID
repo_id = "jainxin/bertopic-patent-model"

# 5. 建立 Hugging Face repo
create_repo(
    repo_id=repo_id,
    repo_type="model",
    exist_ok=True
)

print(f"Repo ready: {repo_id}")

# 6. 建立 README
readme_text = """---
license: mit
tags:
- bertopic
- topic-modeling
- patent-analysis
- kmeans
- sentence-transformers
language:
- en
---

# BERTopic Patent Model

This repository contains a BERTopic model and related artifacts.

## Files
- `bertopic_model.pkl`: full BERTopic pickle model

## Notes
This model was saved with pickle.
To load it later, make sure your Python and library versions are compatible.
"""

with open(os.path.join(save_dir, "README.md"), "w", encoding="utf-8") as f:
    f.write(readme_text)

# 7. 上傳整個資料夾
api = HfApi()
api.upload_folder(
    folder_path=save_dir,
    repo_id=repo_id,
    repo_type="model"
)

print("Upload complete.")

# 8. 測試下載
local_dir = snapshot_download(
    repo_id=repo_id,
    repo_type="model"
)

print("Downloaded to:", local_dir)

# =========================================================
# 19. Set Llama2-generated Topic Labels and Summaries
# =========================================================
full_topics = topic_model.get_topics(full=True)

topic_labels = {}
topic_summaries = {}

for topic_id in full_topics["Main"]:
    if topic_id == -1:
        continue
    topic_labels[topic_id] = full_topics["Main"][topic_id][0][0].strip()
    topic_summaries[topic_id] = full_topics["Summary"][topic_id][0][0].strip()

topic_model.set_topic_labels(topic_labels)

# =========================================================
# 20. Save Topic Labels and Summaries
# =========================================================
df_topic_outputs = pd.DataFrame([
    {
        "Topic": topic_id,
        "Label": topic_labels[topic_id],
        "Summary": topic_summaries[topic_id]
    }
    for topic_id in sorted(topic_labels.keys())
])

df_topic_outputs.to_excel("topic_labels_and_summaries.xlsx", index=False)
print(df_topic_outputs)


# =========================================================
# 21. Visualization for Dynamic Topics
# =========================================================
fig_topics_over_time = topic_model.visualize_topics_over_time(
    topics_over_time,
    top_n_topics=18
)

fig_topics_over_time.write_html("topics_over_time.html")
print("Saved: topics_over_time.html")

topic_model.visualize_barchart()

topic_model.visualize_topics_over_time(topics_over_time)

topic_model.visualize_topics()

topic_model.get_topic_info()

topic_model.get_representative_docs()