# -*- coding: utf-8 -*-
"""python專題預處理.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wDQ_xCbu4097OIG2rW1XFRpAp0pA3Y6y
"""

! nvidia-smi

!pip install spacy openpyxl

!python -m spacy download en_core_web_sm

import pandas as pd
import re
import spacy
import csv
import openpyxl
import numpy as np
import nltk

nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer # import WordNetLemmatizer

patent_data = pd.read_excel('氫燃料電池美國核准專利.xlsx')
test1 = patent_data['Title - DWPI'].fillna('')
test2 = patent_data['Abstract - DWPI'].fillna('')
test = test1 + ' ' + test2

nlp = spacy.load('en_core_web_sm')
spacy_stopwords = spacy.lang.en.stop_words.STOP_WORDS
stop_words_file_path = 'custom_stop_words.xlsx'  # 替換為你的 Excel 文件路徑
custom_stop_words_df = pd.read_excel(stop_words_file_path, header=None)

# 將 Excel 文件中的停用字轉換為列表
excel_stop_words = custom_stop_words_df[0].tolist()

# Remove any NaN values from the list of custom stop words
excel_stop_words = [word for word in excel_stop_words if str(word) != 'nan']

# 將合併後的停用字擴展到 spaCy 的停用字集合中
spacy_stopwords.update(excel_stop_words)
print(f"Total stop words: {len(spacy_stopwords)}")
for word in spacy_stopwords:
  if type(word) is str: # Check if the word is a string before adding to vocabulary
    nlp.vocab[word].is_stop = True
print("Custom stop words have been added successfully.")

# Convert the set of stop words to a list
stop_words_list = list(spacy_stopwords)
print(spacy_stopwords)

# 載入 spaCy 英文模型
lemmatizer = WordNetLemmatizer()
# 獲取單詞的詞性
def get_wordnet_pos(pos_tag):
    """Map POS tag to first character lemmatize() accepts"""
    tag_dict = {"ADJ": wordnet.ADJ,
                "NOUN": wordnet.NOUN,
                "VERB": wordnet.VERB,
                "ADV": wordnet.ADV}
    return tag_dict.get(word, wordnet.NOUN)

def preprocess_text(text):
    if pd.isna(text):
        return ""

     # 🔹 分離數字與英文黏詞（如 13Valve → Valve）
    if re.search(r'\d+[A-Za-z]', text):
        text_parts = re.split(r'(\d+[A-Za-z]+)', text)
        text = ' '.join(
            re.sub(r'\d+', '', part) if re.match(r'\d+[A-Za-z]+', part) else part
            for part in text_parts
        )
    # 🔹 分句
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    # 規則：圖示說明句的開頭
    illustration_patterns = [
        r'^the (drawing|figure|diagram) show(s)?',]

    # 過濾圖示說明句
    filtered_sentences = [
        s for s in sentences
        if not any(re.match(pat, s.strip(), re.I) for pat in illustration_patterns)
    ]
    # 🔹 合併回剩下句子
    cleaned_text = ' '.join(filtered_sentences)

    # 小寫 + 去標點 + 去數字
    cleaned_text = re.sub(r'[^\w\s]', '', cleaned_text.lower())
    cleaned_text = re.sub(r'\d+', '', cleaned_text)

    # spaCy 處理
    doc = nlp(cleaned_text)
    tokens = [
        lemmatizer.lemmatize(token.text.lower(), get_wordnet_pos(token.pos_))
        for token in doc
        if token.is_alpha and token.text.lower() not in stop_words_list
    ]

    return ' '.join(tokens)

# 預處理 test 中的每一句文本
preprocessed_test = [preprocess_text(t) for t in test]

# 如果你想存回 DataFrame 中一起看
patent_data["Document"] = test
patent_data["Processed"] = preprocessed_test

# 顯示結果
print(patent_data[["Document", "Processed"]].head())

# 如果需要儲存
patent_data.to_excel("preprocessed_document.xlsx", index=False)